kind: pipeline
name: default

steps:
- name: portalz-backend
  image: quay.io/quarkus/ubi-quarkus-native-image:19.2.1
  user: root
  commands:
  - whoami
  - pwd
  - ls -lrta
  - unset MAVEN_CONFIG
  - sh ./mvnw -Pnative package 
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: DB_USERNAME
    password:
      from_secret: DB_PASSWORDs