kind: pipeline
name: default

steps:
- name: Native build
  image: quay.io/quarkus/ubi-quarkus-native-image:21.2.0-java11
  user: root
  environment:
    DB_USERNAME:
      from_secret: DB_USERNAME
    DB_PASSWORD:
      from_secret: DB_PASSWORD
  commands:
  - whoami
  - pwd
  - ls -lrta
  - unset MAVEN_CONFIG
  - sh ./mvnw -Pnative package 
- name: Docker 
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: thibaultdct/portalz-api-quarkus
    tags: latest
- name: Caprover
  image: alpine/git
  environment:
    GITHUB_URL:
      from_secret: GITHUB_URL
    GITHUB_USERNAME:
      from_secret: GITHUB_USERNAME
    GITHUB_PASSWORD:
      from_secret: GITHUB_PASSWORD
  commands:
  - echo "Deploying on CapRover..."
  - export DEPLOY_BRANCH=caprover-deploy
  - cd ~
  - git clone $GITHUB_URL
  - cd portalz-api
  - git checkout $DEPLOY_BRANCH || git checkout -b $DEPLOY_BRANCH
  - git rm -rf .
  - git clean -fdx .
  - echo "{\"schemaVersion\":2,\"imageName\":\"thibaultdct/portalz-api-quarkus:latest\"}" > captain-definition
  - git add .
  - git commit -m "📦️ Deploy thibaultdct/portalz-api-quarkus:latest"
  - git push --set-upstream origin $DEPLOY_BRANCH
  - curl -X POST https://captain.cloud2.thibaultdct.fr/api/v2/user/apps/webhooks/triggerbuild?namespace=captain&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InRva2VuVmVyc2lvbiI6ImUxZTViZDNmLTNlOGQtNGI5OC04ZGVkLTVkM2MwNjAzYTA4YiIsImFwcE5hbWUiOiJwb3J0YWx6IiwibmFtZXNwYWNlIjoiY2FwdGFpbiJ9LCJpYXQiOjE2Mjc5MjE4MDZ9.sSXul8CCgjM_C2R8U61CcKbq1vvu8xc0JdeBYYk6y5w